In [1]:
import pandas as pd

In [7]:
# Load data
foods = pd.read_csv('data/asa24/asa24_ingredients/ingredient_frequency_nndc_120721.csv')

In [10]:
foods = foods[foods['glycan_match'] == 1]

In [11]:
foods

,Ingredient description,frequency,glycan_match,note
1,"Alcoholic beverage, beer, regular, all",136,1,NaN
8,"Alcoholic beverage, wine, table, red",104,1,NaN
10,"Alfalfa seeds, sprouted, raw",6,1,NaN
12,"Apple juice, canned or bottled, unsweetened, w...",4,1,NaN
13,"Apple juice, canned or bottled, unsweetened, w...",10,1,NaN
...,...,...,...,...
1193,"Wild rice, cooked",5,1,Wild blend rice
1194,"Yambean (jicama), raw",3,1,NaN
1196,"Yogurt, plain, low fat",101,1,NaN
1197,"Yogurt, plain, skim milk",53,1,greek nonfat
1198,"Yogurt, plain, whole milk",84,1,NaN

In [12]:
foods.to_csv('data/asa24/asa24_ingredients/ingredient_matches_120721.csv', index=None)